const createAction = (type, name) => ({ type, name })
export const chatsLoadedAction = (chats) => ({type: 'CHAT.LIST.LOADED', chats})
export const createChatAction = (name) => createAction('CHAT.LIST.CREATE_CHAT', name)
export const chatCreatedAction = (name) => createAction('CHAT.LIST.CHAT_CREATED', name)
export const chatExistsAction = (name) => createAction('CHAT.LIST.CHAT_EXISTS', name)
export const chatSelectedAction = (name) => createAction('CHAT.LIST.CHAT_SELECTED', name)